name: Publish already generated Sphinx Docs to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@docspublish

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@docspublish
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html   # 👈 your generated site folder
          publish_branch: gh-pages